# Generated by Django 3.1.2 on 2020-12-01 04:34

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Departman Listesi',
                'db_table': 'DepartmentList',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('body', models.TextField(max_length=500, verbose_name='Gövde')),
                ('content', ckeditor.fields.RichTextField()),
                ('addedDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Haber Eklme Tarihi')),
                ('updateDate', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Haber Güncelleme Tarihi')),
                ('newsImg', models.ImageField(blank=True, null=True, upload_to='news/img/', verbose_name='Haber Görseli')),
            ],
            options={
                'verbose_name_plural': 'Ar-Ge Haberler',
                'db_table': 'Haberler',
                'ordering': ['-updateDate'],
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Adı')),
                ('surName', models.CharField(max_length=20, verbose_name='Soyadı')),
                ('email', models.EmailField(default='abcdefg@supsan.com', max_length=50, verbose_name='Email Adresi')),
                ('gender', models.IntegerField(choices=[(1, 'Erkek'), (2, 'Kadın')], default=1, verbose_name='Cinsiyet')),
                ('birthDay', models.DateField(verbose_name='Doğum Tarihi')),
                ('idName', models.CharField(default='12345678911', max_length=11, verbose_name='T.C. Kimlik No')),
                ('country', django_countries.fields.CountryField(default='TR', max_length=2, verbose_name='Uyruk')),
                ('sgNumber', models.IntegerField(blank=True, null=True, verbose_name='Sosyal Güvenlik Numarası')),
                ('sNumber', models.IntegerField(blank=True, null=True, verbose_name='Sicil No')),
                ('respons', models.IntegerField(choices=[(1, 'Araştırmacı'), (2, 'Teknisyen'), (3, 'Destek Personeli')], default=1, verbose_name='Ar-Ge Görevi')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='İşe Başlangıç Tarihi')),
                ('finisDate', models.DateField(blank=True, null=True, verbose_name='İşten Ayrılış Tarihi')),
                ('rdfinisDate', models.DateField(blank=True, null=True, verbose_name='Ar-Ge Ayrılış Tarihi')),
                ('rdStartDate', models.DateField(blank=True, null=True, verbose_name='Ar-Ge Merkezi İşe Başlama Tarihi')),
                ('graduated', models.IntegerField(choices=[(0, 'Diğer'), (1, 'Lise'), (2, 'Lise (Öğrenci)'), (3, 'Ön Lisans'), (4, 'Ön Lisans (Öğrenci)'), (5, 'Lisans'), (6, 'Lisans (Öğrenci)'), (7, 'Yüksek Lisans'), (8, 'Yüksek Lisans (Öğrenci)'), (9, 'Doktora'), (10, 'Doktora (Öğrenci)')], default=0, verbose_name='Tahsil Durumu')),
                ('hschool', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lise Adı')),
                ('hschooldist', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lise Bölümü')),
                ('huschooldist', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bölümü (Ön Lisans)')),
                ('universitydist', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bölümü (Lisans)')),
                ('masteruniversitydist', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bölümü (Yüksek Lisans')),
                ('druniversitydist', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bölümü (Doktora')),
                ('userImg', models.ImageField(blank=True, null=True, upload_to='personels/img/', verbose_name='Kullanıcı Profil Resmi')),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='PersonelDepartman', to='core.departmentlist', verbose_name='Çalıştığı Departman')),
            ],
            options={
                'verbose_name_plural': 'Ar-Ge Personeller',
                'db_table': 'personel',
            },
        ),
        migrations.CreateModel(
            name='UniversityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Ar-Ge Universite',
                'db_table': 'UniversityList',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjeDurumu', models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Tamamlandı'), (2, 'Devam Ediyor'), (3, 'İptal')], default=0, verbose_name='Proje Durumu:')),
                ('ProjeKodu', models.CharField(max_length=50, verbose_name='Proje Kodu:')),
                ('ProjeAdi', models.CharField(max_length=120, verbose_name='Proje Adı:')),
                ('ProjeBaslamaTarihi', models.DateField(blank=True, null=True, verbose_name='Proje Başlama Tarihi:')),
                ('ProjeBitisTarihi', models.DateField(blank=True, null=True, verbose_name='Proje Bitiş Tarihi:')),
                ('TamamlanmaYuzdesi', models.FloatField(default=0, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Projenin Tamamlanma Yüzdesi')),
                ('ProjeSuresiAdamAy', models.IntegerField(blank=True, null=True, verbose_name='Proje Adam Ay Süresi:')),
                ('ProjeKonusu', models.CharField(max_length=1000, verbose_name='Proje Konusu:')),
                ('ProjeOzeti', models.CharField(max_length=1000, verbose_name='Proje Özeti:')),
                ('UlusalDestek', models.BooleanField(default=False, verbose_name='Ulusal Destek Prgramı Var Mı?')),
                ('UlusalDestekTanım', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ulusal Destek Adı:')),
                ('OzKaynakTutar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Öz Kaynaklarca Karşılanan tutar (TL):')),
                ('DestekTutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Destek Tutarı (TL):')),
                ('ToplamProjeButcesi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Proje Bütçesi')),
                ('HizmetAlimiKonusu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hizmet Alımı Konusu:')),
                ('HizmetAlimi', models.IntegerField(choices=[(0, 'Hizmet Alımı Yapılmadı'), (1, 'Yurt İçi'), (2, 'Yurt Dışı'), (3, 'Her İkisi')], default=0, verbose_name='Hizmet Alımı Yapılan Yer')),
                ('YurtIciHizmetAlimiTutari', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yurt İçi Hizmet Alımı Tutarı (TL):')),
                ('YurtDisiHizmetAlimiTutari', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yurt Dışı Hizmet Alımı Tutarı (TL):')),
                ('ProjeKonusunuBelirleyenIhtiyaclar', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Projenin Konusunu Belirleyen İhtiyaçlar:')),
                ('ProjeKapsamindaYapilacakFaaliyetler', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Proje Kapsamında Yapılacak Faaliyetler:')),
                ('ProjeninYenilikciYonuArgeNiteligi', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Projenin Yenilikçi Yönü ve AR-GE Niteliği:')),
                ('ProjeninBeklenenCiktilariFaydalari', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Projenin Beklenen Çıktıları:')),
                ('ProjePersonel', models.IntegerField(blank=True, null=True, verbose_name='Projedeki Personel Sayısı:')),
                ('UniversiteSanayiIsbirligiProjesi', models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Evet'), (2, 'Hayır')], default=0, verbose_name='Üniversite-Sanayi İşbirliği Mi?')),
                ('FirmalarArasiArgeIsbirligi', models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Evet'), (2, 'Hayır')], default=0, verbose_name='Firmalar Arası Ar-Ge İşbirliği Mi?')),
                ('SipariseDayaliArgeProjesi', models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Evet'), (2, 'Hayır')], default=0, verbose_name='Siparişe Dayalı Ar-Ge Projesi Mi?')),
                ('ProjeGuncellemeTarihi', models.DateField(blank=True, null=True, verbose_name='Projenin Güncelleme Tarihi:')),
                ('PRojeCiktisi', models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Ticari Ürün'), (2, 'Proses Geliştirme'), (3, 'Bilgi Birikimi ve Yetkinlik Kazanımı')], default=0, verbose_name='Projenin Çıktısı')),
                ('deneme', models.CharField(max_length=50)),
                ('ProjeYurutucusu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Proje_Y', to='core.personel', verbose_name='Proje Yürütücüsü')),
                ('projecalis', models.ManyToManyField(related_name='Proje_adam_ay', to='core.Personel', verbose_name='Projede Çalışan Personeller:')),
            ],
            options={
                'verbose_name_plural': 'Ar-Ge Projeler',
                'db_table': 'Projeler',
            },
        ),
        migrations.AddField(
            model_name='personel',
            name='druniversity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='doktora', to='core.universitylist', verbose_name='Universite (Doktora)'),
        ),
        migrations.AddField(
            model_name='personel',
            name='huschool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='onlisans', to='core.universitylist', verbose_name='Universite (Ön Lisans)'),
        ),
        migrations.AddField(
            model_name='personel',
            name='masteruniversity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='master', to='core.universitylist', verbose_name='Universite (Yüksek Lisans)'),
        ),
        migrations.AddField(
            model_name='personel',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lisans', to='core.universitylist', verbose_name='Universite (Lisans)'),
        ),
        migrations.CreateModel(
            name='IsPaketiekle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPaketino', models.IntegerField(choices=[(1, 'IP.1'), (2, 'IP.2'), (3, 'IP.3'), (4, 'IP.4'), (5, 'IP.5'), (6, 'IP.6')], default=1, verbose_name='İş Paketi No:')),
                ('isPaketiadi', models.CharField(default='İş Paketi Başlığı', max_length=100, verbose_name='İş Paketi Başlığı')),
                ('baslangicTarihi', models.DateField(blank=True, null=True, verbose_name='İş Paketi Başlangıcı')),
                ('bitisTarihi', models.DateField(blank=True, null=True, verbose_name='İş Paketi Bitişi')),
                ('tamamlanmaOranı', models.FloatField(default=0, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Projenin Tamamlanma Yüzdesi')),
                ('faaliyet', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Yapılacak Faaliyetler')),
                ('projeKodu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects', verbose_name='Proje Kodu')),
                ('sorumlu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personel', verbose_name='İş Paketi Sorumlusu')),
            ],
            options={
                'verbose_name_plural': 'Proje Ispaketleri',
                'db_table': 'IsPaketleri',
            },
        ),
        migrations.CreateModel(
            name='AdamAy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Dönem:')),
                ('adamAylar', models.DecimalField(decimal_places=2, default=0.0, max_digits=2, verbose_name='Adam Ay:')),
                ('projeAdamAy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personel', verbose_name='Proje Çalışan')),
                ('projeKodu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects', verbose_name='Proje Kodu')),
            ],
            options={
                'verbose_name_plural': 'Adam Ay',
                'db_table': 'AdamAy',
            },
        ),
    ]
