# Generated by Django 3.1.2 on 2020-12-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='deneme',
        ),
    ]
