# Generated by Django 3.1.2 on 2020-12-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_projects_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projecalis',
        ),
        migrations.AddField(
            model_name='projects',
            name='projecalis',
            field=models.ManyToManyField(related_name='Proje_adam_ay', through='core.AdamAy', to='core.Personel', verbose_name='Projede Çalışan Personeller:'),
        ),
    ]
