# Generated by Django 3.1.2 on 2020-12-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201207_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adamay',
            name='projeAdamAy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personel', verbose_name='Projede Çalışan Personel'),
        ),
        migrations.AlterField(
            model_name='adamay',
            name='projeKodu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects', verbose_name='Proje Kodu'),
        ),
    ]
