# Generated by Django 3.1.1 on 2020-12-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201207_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='UlusalDestekTanım',
            new_name='UlusalDestekTanim',
        ),
    ]
