# Generated by Django 3.1.1 on 2020-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201213_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgeTesvik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dönem')),
                ('argetotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Toplam Arge Harcaması')),
                ('hibe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Nakit Alınan Hibe')),
                ('sgktesvik5746', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='5746 SGK Teşvik')),
                ('gelirtesvik5746', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='5746 Gelir Teşvik')),
                ('argeindirim', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kurumlar-Geçici Ar-Ge İndirimi')),
            ],
        ),
    ]
