# Generated by Django 3.1.1 on 2020-12-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_argetesvik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argetesvik',
            options={'verbose_name_plural': 'ArgeTesvik'},
        ),
        migrations.AlterModelTable(
            name='argetesvik',
            table='ArgeTesvik',
        ),
    ]
