# Generated by Django 3.1.1 on 2020-12-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201220_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argetesvik',
            name='argeindirim',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Kurumlar-Geçici Ar-Ge İndirimi'),
        ),
        migrations.AlterField(
            model_name='argetesvik',
            name='ayliktesvikyuzde',
            field=models.IntegerField(default=0, editable=False, verbose_name='Ar-Ge Teşviği Oran'),
        ),
        migrations.AlterField(
            model_name='argetesvik',
            name='hibe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Nakit Alınan Hibe'),
        ),
    ]
