# Generated by Django 3.1.1 on 2020-12-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201227_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bildiri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(choices=[(0, 'Makale'), (1, 'Bildiri'), (2, 'Poster')], default=0)),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250, verbose_name='Yayınlanan Yer')),
                ('pubdate', models.DateField(verbose_name='Yayınlanma Tarihi')),
                ('owner', models.CharField(max_length=250, verbose_name='Yazarlar')),
            ],
            options={
                'verbose_name_plural': 'Bildiri',
                'db_table': 'Bildiri',
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Patent'), (2, 'Faydalı Model')], default=0)),
                ('area', models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Ulusal'), (2, 'Uluslar Arası')], default=0)),
                ('code', models.CharField(max_length=50, verbose_name='Buluş Kodu')),
                ('inventor', models.CharField(max_length=50, verbose_name='Buluşçular')),
                ('topic', models.TextField(verbose_name='Buluş Konusu')),
                ('consultant', models.CharField(max_length=50, verbose_name='Patent Danışmanı')),
                ('apldate', models.DateField(verbose_name='Başvuru Tarihi')),
                ('aprdate', models.DateField(blank=True, null=True, verbose_name='Tescil Tarihi')),
                ('situation', models.IntegerField(choices=[(0, 'Başvuru'), (1, 'Belge Alındı'), (2, 'Koruma Süresi Doldu'), (3, 'Terk Edildi'), (4, 'Reddedildi'), (5, 'Ülke Aşaması')])),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Durum hk. Açıklama')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projects', verbose_name='İlgili Proje Kodu')),
            ],
            options={
                'verbose_name_plural': 'Patent',
                'db_table': 'Patent',
            },
        ),
    ]
