# Generated by Django 3.1.1 on 2020-12-28 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bildiri_patent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects', verbose_name='İlgili Proje Kodu'),
        ),
    ]
