# Generated by Django 3.1.1 on 2020-12-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201228_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildiri',
            name='area',
            field=models.IntegerField(choices=[(0, 'Seçiniz'), (1, 'Ulusal'), (2, 'Uluslar Arası')], default=0),
        ),
    ]
