# Generated by Django 3.1.1 on 2020-12-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bildiri_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildiri',
            name='file_bildiri',
            field=models.FileField(blank=True, null=True, upload_to='bildiri/'),
        ),
        migrations.AddField(
            model_name='patent',
            name='file_patent',
            field=models.FileField(blank=True, null=True, upload_to='patent/'),
        ),
    ]
