# Generated by Django 3.1.1 on 2020-12-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201231_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildiri',
            name='file_bildiri',
            field=models.FileField(blank=True, null=True, upload_to='bildiri/files/'),
        ),
    ]
