# Generated by Django 3.1.1 on 2021-01-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201231_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='adamay',
            name='durum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
