# Generated by Django 3.1.1 on 2021-01-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_adamay_durum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adamay',
            name='durum',
        ),
    ]
