# Generated by Django 3.1.1 on 2021-01-03 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_adamay_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adamay',
            name='adamAylar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Adam Ay:'),
        ),
    ]
