# Generated by Django 3.1.1 on 2021-01-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210103_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='personel',
            name='expense_center',
            field=models.IntegerField(blank=True, choices=[(0, '4001'), (1, '4002')], default=0, null=True, verbose_name='Masraf Yeri'),
        ),
    ]
