# Generated by Django 3.1.1 on 2021-01-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210109_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='expensecenter',
            field=models.IntegerField(blank=True, choices=[(4001, '4001'), (4002, '4002')], default=4001, null=True, verbose_name='Masraf Yeri'),
        ),
    ]
